### ISSUE TITLE
Zakodowanie layoutu

### ISSUE THREAD

**Issue by Dziabodo** [DrupalCampWroclaw/organizacyjne#11]
Siemka,

Ja postaram sie jutro zakodować layout do strony. Chcę zrobic to na Omedze 3 bo daje fajne wbudowane możliwości do kodowania responsywnego dla 4 mediów Full hd nomalny tablet i smartfon. Chyba, że chcecie aby było to na innym to ok. Tutaj głównie pytanie do Gena czy Omega moze być czy wolisz Zen albo Bootstrapa:) 

Pozdr

**Comment by grzegorzbartman** [comment]
Ustaliliśmy telefonicznie, że zostaniemy przy Zen

**Comment by Dziabodo** [comment]
Potwierdzam
