### ISSUE TITLE
Plakat na potrzeby informacji prasowych

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne#12]
![plakat_mockup_v1](https://f.cloud.github.com/assets/1450802/1846560/4df81c48-7604-11e3-8017-6052b137ba65.png)

To jest propozycja tekstów i rozmieszczenia elementów na plakacie. Dajcie znać czy taka koncepcja Wam odpowiada. Oczywiście trzeba dopracować to graficznie.

W sekcji organizatorzy jeśli chcecie wstawić jakieś swoje logotypy to piszcie też tutaj lub do Staszka (Karol powinien go dzisiaj dodać do githuba).

Wersja w formacie GIMPa w repozytorium GIT.

**Comment by grzegorzbartman** [comment]
https://github.com/DrupalCampWroclaw/organizacyjne/tree/master/plakat link do plakatu w wersji GIMPa (warstwy do edycji)

**Comment by Dziabodo** [comment]
Staszek jest dodany Safegraph to on :) jego email ak by ktoś chcial to safegraph@gmail.com

**Comment by grzegorzbartman** [comment]
Jaro, miałeś napisać jakieś uwagi odnośnie plakatu.

**Comment by grzegorzbartman** [comment]
Staszek myślę, że możesz się zająć tym plakatem, skoro nikt nie zgłasza uwag.

**Comment by grzegorzbartman** [comment]
Plakat przygotować w formacie A3, będzie od razu do druku.

**Comment by grzegorzbartman** [comment]
Plakaty https://github.com/DrupalCampWroclaw/organizacyjne/issues/12

Smycze https://github.com/DrupalCampWroclaw/organizacyjne/issues/15

Komunikujmy się w poszczególnych sprawach przez issue tracker na github.

W dniu 12 stycznia 2014 20:50 użytkownik Safegraph <notifications@github.com

> napisał:
> 
> Posiadacie jakąś treść do plakatu??
> Tak abym wiedział co mniej więcej wrzucić??
> Jakaś treść do plakatów.
> Odnośnie smyczy: gdzie drukujecie: jakaś specyfikacja, strona abym mógł
> pobrać makiete, albo wytyczne pod jaki rozmiar wykonać.
> 
> pzdr Stanisław
> 
> 2014/1/12 grzegorzbartman notifications@github.com
> 
> > Plakat przygotować w formacie A3, będzie od razu do druku.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/DrupalCampWroclaw/organizacyjne/issues/12#issuecomment-32122339>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DrupalCampWroclaw/organizacyjne/issues/12#issuecomment-32131771
> .

## 

Pozdrawiam/Kind regards
Grzegorz Bartman
mobile. +48 882 515 514
e-mail: grzegorz.bartman@openbit.pl
skype: grzegorzbartman

openBIT - Drupal Experts
ul. Ostrowskiego 30/36, 53-238 Wrocław, Poland
phone: +48 71 71 88 457
www.openbit.pl www.openbitdrupal.com
biuro@openbit.pl
