### ISSUE TITLE
Smycze - projekt graficzny

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne#15]
Potrzebny projekt graficzny smyczy, wysokość 20mm.

**Comment by grzegorzbartman** [comment]
#16

**Comment by Safegraph** [comment]
W załączniku przesyłam plik podglądowy i plik otwarty smyczy. Wytyczne
spadów i margin wewnętrzny pobraney ze strony.

Smycz prosta bez zatrzasków dodatkowych.

2014/1/13 grzegorzbartman notifications@github.com

**Comment by grzegorzbartman** [comment]
Dzięki za projekt.
Zrób smycz bez daty. W miejsce daty wstaw adres strony www.drupalcampwroclaw.pl Będziemy mieli projekt na następny rok.
