### ISSUE TITLE
Wideo z wykładów - wybrać wykonawcę

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne#18]
Zapytać się TV STYK http://www.styk.pwr.wroc.pl/ czy mogą nam nagrać wykłady. Rok temu na Sesji Linuksowej bardzo fajnie to zrobili, był też streaming na żywo z konferencji. 
Kto się tym zajmie?

**Comment by grzegorzbartman** [comment]
Jaro miales z kims rozmawiac o wideo, cos juz wiadomo?

**Comment by jaro2801** [comment]
Jestem umówiony na poniedziałek.

**Comment by grzegorzbartman** [comment]
Sami będziemy nagrywać z pomocą ASI
