### ISSUE TITLE
Hotel - dla prelegentów oraz uczestników, party w hotelu

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne#19]
W tym roku chcemy wybrać lepszy hotel niż hostel w poprzednim roku. 
Chcemy od hotelu uzyskać zniżkę dla uczestników konferencji i wynegocjować cenę do 99 zł za osobę za jedną noc. Hotel (nie hostel, najlepiej 3-gwiazdkowy) musi być blisko rynku a także w miarę blisko przystanku tramwajowego aby dojechać na PWr.
W hotelu powinien też być większy bar/sala żeby można było tam zorganizować Drupal Party. 
Ktoś musi się przejść po hotelach we Wrocławiu i porozmawiać o możliwych opcjach. Kto chętny do tego zadania?

**Comment by grzegorzbartman** [comment]
Hotel może zostać naszym sponsorem/partnerem, jeśli zaoferuje odpowiednie zniżki, możemy go promować na stronie internetowej konferencji.

**Comment by jaro2801** [comment]
Ja się zajmę tym zadaniem.
