### ISSUE TITLE
Badge na stronę - grafiki

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne#33]
Grafiki 300x300px z logo konferencji i napisami (jeden napis to jedna grafika), coś jak http://dcwroc.pl/materialy-reklamowe 
- jestem uczestnikiem
- jestem prelegentem
- patronat medialny
- sponsor diamentowy
- sponsor platynowy
- sponsor złoty
- sponsor srebrny
- sponsor brązowy 
- sponsor imprezy - albo sponsor Drupal Party

**Comment by Safegraph** [comment]
Paczka z avatarami + plik otwarty w PSD.

W dniu 13 stycznia 2014 08:00 u¿ytkownik grzegorzbartman <
notifications@github.com> napisa³:

**Comment by grzegorzbartman** [comment]
Gdzie wysłałeś załącznik? Tutaj go nie widzę. W repo też nie widzę commitów https://github.com/DrupalCampWroclaw/organizacyjne/commits/master

**Comment by Safegraph** [comment]
W załączniku wiadomości.
Podsyłam jeszcze raz. Załacznik wiadomosci.

W dniu 13 stycznia 2014 20:38 użytkownik grzegorzbartman <
notifications@github.com> napisał:

**Comment by annamroczko** [comment]
Ja też nie widzę załączników. Wyślij grafiki na poczŧę info@drupalcampwroclaw.pl i każdy je dostanie :)

**Comment by jaro2801** [comment]
Według mnie grafiki są okej. Do poprawy są tylko daty(konferencja jest 16-18 Maja) i avatarach zmień "Drupal Party" na "Drupal Party Sponsor". Ode mnie tyle co byłoby do poprawy.

**Comment by grzegorzbartman** [comment]
Jest ok :)
Wrzuciłem to do repozytorium. Potrzebujemy jeszcze pliki z tekstami w języku angielskim.

**Comment by Safegraph** [comment]
Podaj teksty po anngielsku. Jutro sobota wiec mogę troche więcej
posiedzieć, bo w tygodniu zalatany pracą jestem.
Proszę o podanie tekstów na maila:D

W dniu 17 stycznia 2014 08:09 użytkownik grzegorzbartman <
notifications@github.com> napisał:

**Comment by annamroczko** [comment]
Jestem uczestnikiem – I'm attending!
Sponsor Drupal Party – Drupal Party Sponsor
Jestem prelegentem – I'm a Speaker
Patronat medialny – Media Partner
Sponsor diamentowy – Diamond Sponsor
Sponsor platynowy – Platinum Sponsor
Sponsor złoty – Gold Sponsor
Sponsor srebrny – Silver Sponsor
Sponsor brązowy – Bronze Sponsor

**Comment by grzegorzbartman** [comment]
Badge są w repo

**Comment by grzegorzbartman** [comment]
W angielskich grafikach miesiąc jest po polsku, np: http://www.drupalcampwroclaw.pl/sites/default/files/badges/1en.jpg

Do zmiany na zapis liczbowy 16-18.05.2014
