### ISSUE TITLE
Spotkania organizacyjne - raz na tydzień

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne#34]
Proponuję od kolejnego tygodnia organizować raz w tygodniu spotkanie organizacyjne aby robić podsumowanie tego co zostało zrobione w poprzednim tygodniu oraz tego co będzie wykonane w następnym tygodniu/tygodniach. W ten sposób będziemy bardziej regularnie pracować nad przygotowaniem konferencji. 
Napiszcie w jakie dni i godziny pasują Wam takie spotkania.
Jako miejsce proponuję siedzibę Droptica (Ostrowskiego 30) lub Politechnikę Wrocławską (w tym nowym studenckim budynku powinno być miejsce aby pogadać.

Dni i godziny jakie mi pasują:
- poniedziałek, wtorek, czwartek, piatek 14-18

**Comment by grzegorzbartman** [comment]
Osoby nie z Wrocławia mogą się z nami łączyć przez Google Hangouts.

**Comment by jaro2801** [comment]
Jestem za takimi spotkaniami. Ustalmy pierwsze spotkanie a kolejne będziemy może ustalać na koniec spotkania.

**Comment by grzegorzbartman** [comment]
proponuje najblizszy poniedzialek, do ustalenia miejsce i godzina. Jaro zajmiesz sie tym?
