### ISSUE TITLE
News o helion do przetłumaczenia

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne#38]
Książki dla uczestników konferencji od wydawnictwa Helion

Macie ochotę na którąś z książek na temat Drupala? 
Wydawnictwo Helion ufundowało 5 publikacji, które będziecie mogli wygrać w jednym z konkursów podczas Drupal Camp Wrocław 2014! 

Na trzecią edycję konferencji DrupalCampWrocław zapraszamy od 16 do 18 maja 2014!

**Comment by annamroczko** [comment]
Books for attendees founded by Helion publishing house

Interested in getting one of the books about Drupal?
Helion publishing house founded 5 books, which you can win in one of the drawings during DrupalCamp Wrocław 2014!

Join us for the third edition of the conference on May 16-18, 2014!

**Comment by grzegorzbartman** [comment]
Dodane na stronę. Zamykam.
