### ISSUE TITLE
Tlumaczenie - krotkie info o konferencji

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne#39]
Wstawie gdzies na stronie krotkie info o konferencji. Ponizej tekst do przetlumaczenia.

Czym jest DrupalCamp Wroclaw?
- konferencja dla osob zainteresowanych drupalem (uzytkownikow, programistow, manadzerow firm tworzacych serwisy internetowe i aplikacje internetowe)
- wstep jest bezplatny
- dla zarejestrowanych na stronie darmowe gadzety
- 3 dniowa konferencja
- impreza integracyjna w sobote

**Comment by annamroczko** [comment]
Tłumaczenie "Czym jest DCW?" i newsa o Helionie i książkach:)

Pozdrawiam,
Anna Mroczko

Tel. 535 873 928
E-mail: anka.mroczko@gmail.com

W dniu 15 lutego 2014 12:57 użytkownik grzegorzbartman <
notifications@github.com> napisał:

**Comment by annamroczko** [comment]
What is DrupalCamp Wrocław?

a conference for all interested in Drupal (users, programmers, managers of companies creating websites and apps)
free to attend 
free gadgets for attendees registered on the website
a three-day conference
Drupal party on Saturday
