### ISSUE TITLE
Catering

### ISSUE THREAD

**Issue by MaciejLukianski** [DrupalCampWroclaw/organizacyjne#5]
Chętnie tylko widziałbym potrawy i oprawę na wyższym poziomie.
Zastanawiam się czy nie moglibyśmy zorganizować jakoś ciekawiej posiłków dla prelegentów i gości. Fajnym rozwiązaniem byłby catering w jakiejś sali, lub nawet na dole, gdzie wszyscy mogliby coś zjeść i przy okazji porozmawiać. 

Nie wiem tylko czy finansowo udźwigniemy wykarmienie wszystkich gości. Trzeba by to jakoś rozwiązać. Może pierwszych 40stu albo że można wykupić voucher na obiad na stronie przed przyjazdem.

**Comment by grzegorzbartman** [comment]
Mamy na oku taką firmę http://www.catering-quantum.pl/ Robią dobre jedzenie, bliżej konferencji zapytamy o ofertę. 
Jeśli sponsorzy dopiszą to powinno się udać zorganizować katering dla wszystkich uczestników.

**Comment by jaro2801** [comment]
Jeśli będzie odpowiednie zainteresowanie sponsorów to myślę, że uda się zorganizować katering dla wszystkich uczestników.

Gdyby jednak zabrakło funduszy to kiedyś rozmawialiśmy o tym, żeby ludzie chętni na zjedzenie takiego grupowego obiadu wpłacali jakąś kwotę załóżmy ok.30-40 zł. Byłoby to jakieś wsparcie dodatkowe dla nas a oprócz obiadów można też dorzucić np. bilety 72h na komunikację miejską we Wrocławiu dla osób co wpłaciły taką kwotę. Takie wpłaty pozwolą nam też bardziej precyzyjnie ustalić ile gadżetów zrobić.

**Comment by grzegorzbartman** [comment]
Kateringiem zajmie się knajpa z UWr
