### ISSUE TITLE
Informacja prasowa

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne#6]
Na wiki https://github.com/DrupalCampWroclaw/organizacyjne/wiki/Informacja-prasowa jest informacja prasowa w poprzedniej edycji konferencji. Na jej podstawie można przygotować nową informację prasową. O sponsorach i prelegentach jeszcze nie mamy informacji.

**Comment by Luposodrom** [comment]
DrupalCamp Wrocław 2014 - konferencja poświęcona w 100% niebieskiej kropli
17-18.05.2014 Wrocław

Już po raz trzeci zapraszamy do Wrocławia na konferencję DrupalCamp. Inicjatywa ta organizowana jest z myślą o polskiej społeczności zainteresowanej platformą Drupal – zarówno programistów, jak i studentów czy przedsiębiorców.

Celem dwudniowej konferencji jest wymiana doświadczeń miedzy specjalistami i mniej doświadczonymi użytkownikami, jest to także doskonałe miejsce na promocje firm, związanych z CMS Drupal (aktywny udział w konferencji zapowiedziało wielu polskich specjalistów tego systemu zarządzania treścią). 

Głównym powodem konferencji jest rosnąca popularność CMS Drupal w Polsce, o czym świadczy fakt, że w minionym roku na rynku wydawniczym pojawiło się aż 6 książek poświęconych tylko obsłudze tego systemu zarządzania treścią. Fakt ciągłego wzrostu społeczności programistów i użytkowników widać także po ilości nowo powstałych portali poświęconych wyłącznie CMS Drupal, serii spotkań społeczności w całym kraju, a także dużej ilości ofert o stworzenie aplikacji właśnie w tej technologii.  

Drupal to system zarządzania treścią (ang. Content Management System – CMS) na stronach internetowych. Podczas konferencji we Wrocławiu specjaliści będą prowadzić wykłady i odpowiadać na pytania uczestników.
Konferencja co rok przyciąga większą liczbę miłośników Drupala. Ostatnia zgromadziła ok. 150 uczestników, w tym kilkudziesięciu z różnych państw Europy. Zainteresowanie z roku na rok rośnie, więc podczas DrupaCamp 2014 przygotowujemy się na przyjęcie ponad 200 osób.Swój udział już zapowiedziało wielu specjalistów z kraju i zagranicy. Planowanych jest ok. 20 sesji, w tym część po angielsku. 

Plan konferencji oraz informacje o prelegentach wkrótce!

Wszyscy zainteresowani wygłoszeniem prelekcji na wybrany przez siebie temat mogą zgłosić swoją propozycję na stronie www.drupalcampwroclaw.pl

Konferencje organizuje Akademickie Stowarzyszenie Informatyczne i pasjonaci Drupala. Zapraszamy 17 i 18 maja 2014 roku do Auli Politechniki Wrocławskiej (ul. Wybrzeże Wyspiańskiego 27). Wstęp bezpłatny!

Więcej informacji na www.drupalcampwroclaw.pl
oraz na Facebooku https://www.facebook.com/DrupalCampWroclaw

Sponsorzy: Omega8.cc, SEMtec, InternetDevels, Media Regionalne oraz Fingo.

**Comment by grzegorzbartman** [comment]
Dzięki za tekst!

Wstrzymamy się jeszcze 1-2 dni z wysyłaniem tej informacji. 

Na google docs https://docs.google.com/a/droptica.com/spreadsheet/ccc?key=0ArpR5hFwr87ndG5ERDF1WW13RVRkZXNkeTY0WDF0ZXc#gid=0 zrobiłem dokument, gdzie będzie można wpisać komu i kiedy wysłaliśmy maila z informacją o konferencji. Będzie tam też można notować czy był odzew. 
Karol może Ci dać uprawnienia do edycji tego dokumentu.

**Comment by Luposodrom** [comment]
Drupal Camp Wrocław 2014 - konferencja poświęcona w 100% niebieskiej kropli! 16-18.05.2014 Wrocław

Już po raz trzeci zapraszamy do Wrocławia na konferencję Drupal Camp. Inicjatywa ta organizowana jest z myślą o polskiej społeczności zainteresowanej platformą Drupal – zarówno programistów, jak i studentów czy przedsiębiorców. Głównym powodem konferencji jest rosnąca popularność CMS Drupal w Polsce, o czym świadczy fakt, że w minionym roku na rynku wydawniczym pojawiło się aż 6 książek poświęconych tylko obsłudze tego systemu zarządzania treścią, a na świecie istnieje już ponad milion stron opartych o platformę Drupal. Jednocześnie jest to czas i miejsce na wymianę doświadczeń i nawiązania ciekawych znajomości. Ponad to po konferencji przewidujemy spotkanie towarzyskie dla wszystkich uczestników w jednym z wrocławskich klubów.

Podczas trzydniowej konferencji we Wrocławiu znani prelegenci będą prowadzić wykłady i odpowiadać na pytania uczestników. Swoją obecność zapowiedziało już kliku cenionych specjalistów: Jeffrey McGuire (Acquia, Niemcy), Jakob Persson (Leancept, Szwecja), Rafał Enden (eeShore, Polska), Maciej Łukiański (Droptica, Polska), Sławek Szulczewski (Drupalomania, Polska), Grzegorz Bartman (Droptica, Polska) oraz Piotr Knapik (Schibsted Tech Polska, Polska). Lista prelegentów cały czas rośnie, dlatego do końca kwietna z pewnością zapowiemy jeszcze klika ciekawych nazwisk. 

Jednocześnie w dalszym ciągu istnieje możliwość zgłaszania swoich prelekcji. 
Zapraszamy na:
http://www.drupalcampwroclaw.pl/node/add/session

Konferencja co rok przyciąga większą liczbę miłośników Drupala. Ostatnia zgromadziła ok. 150 uczestników, w tym kilkudziesięciu z różnych państw Europy. Zainteresowanie z roku na rok rośnie, więc podczas Drupal Camp 2014 przygotowujemy się na przyjęcie ponad 200 osób.  Planowanych jest ok. 20 sesji, w tym część po angielsku. 

W związku z rosnącym zainteresowaniem zarówno konferencją Drupal Camp Wrocław, jak i samą platformą Drupal, w tym roku rozszerzyliśmy zakres konferencji. Podczas tegorocznej edycji organizujemy dodatkowy dzień w całości przeznaczony na warsztaty. Podczas zajęć doświadczeni deweloperzy uczą jak posługiwać się Drupalem oraz jak konfigurować podstawowe moduły tak aby po zakończeniu kursu, można było stworzyć własną witrynę ze średnio zaawansowanymi funkcjonalnościami. Kurs odbędzie się 16 maja i potrwa około 5 godzin, a po jego ukończeniu możliwe jest uzyskanie potwierdzenia o odbyciu szkolenia w CMS Drupal.

Wszystkich zainteresowanych uczestnictwem w Drupal Camp Wrocław 2014 zapraszamy do rejestracji na www.drupalcampwroclaw.pl. Udział w konferencji jest bezpłatny, a wszyscy zarejestrowani użytkownicy otrzymają gadżety i będą mieli możliwość wzięcia udziału w konkursach z nagrodami.

Konferencje organizuje Akademickie Stowarzyszenie Informatyczne i pasjonaci Drupala. Konferencja odbędzie się 16, 17 i 18 maja 2014 roku we Wrocławiu. Wstęp wolny!

Więcej informacji: www.drupalcampwroclaw.pl
Śledź nas na bieżąco na:
- Facebook  http://www.facebook.com/drupalcampwroclawpl
- Twitter http://twitter.com/drupalcamp_wroc
- Google+ https://plus.google.com/+DrupalcampwroclawPl/posts

Partnerzy medialni: Web.gov.pl, DlaStudenta.pl, Webmastah, Beautiful Code, Politechnika Wrocławska, Żak, Akademickie Radio Luz.
