### ISSUE TITLE
Przetłumaczenie informacji prasowej na język angielski

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/organizacyjne#7]
Zrobić jak będzie zrobione zadanie #6

**Comment by annamroczko** [comment]
DrupalCamp Wrocław 2014 – conference devoted in 100% to the blue drop

17-18.05.2014 Wrocław

For the third time we are pleased to invite you to Wrocław for DrupalCamp conference. The enterprise is intended mostly for Polish community interested in Drupal platform – including programmers, students as well as entrepreneurs.

The aim of this two-day conference is the exchange of experience and knowledge between specialists and less experienced users; it is also a great place to promote firms linked with CMS Drupal (many Polish Drupal experts have already announced their active participation in the conference).

The main reason for the organization of the event is the growing popularity of CMS Drupal in Poland. This can be seen on the publishing market where, in the previous year, 6 books about CMS Drupal were published. The growing number of programmers and users may also be noted along with the increasing number of portals devoted exclusively to CMS Drupal, in the series of meetings around the country concerned with the software and in the frequency of enquiries about applications based on the technology.

Drupal is content management system software (CMS) by many considered as one of the best. During the conference in Wrocław, specialists will give lectures and answer participants' questions.

Every year more and more Drupal lovers are coming to the conference. Last time we welcomed about 150 attendants, including several dozens from different European countries. The popularity of the conference is constantly growing, so we are expecting over 200 participants during DrupalCamp 2014. Many specialists from home and abroad have already announced their coming. Around 20 sessions are being planned, some of which in English. 

The whole schedule and information about the conference soon!

If you are interested in giving lectures on your own topic, please follow the link to our website www.drupalcampwroclaw.pl

The conference is organized by Akademickie Stowarzyszenie Informtyczne and Drupal lovers. Join us on May 17-18, 2014 in the Hall of Main Building of the University of Technology in Wrocław (Wybrzeże Wyspiańskiego 27). It is free!

More information at www.drupalcampwroclaw.pl

and on Facebook https://www.facebook.com/DrupalCampWroclaw

Sponsors: Omega8.cc, SEMtec, InternetDevels, Media Regionalne and Fingo.

**Comment by grzegorzbartman** [comment]
Dodałem do wiki https://github.com/DrupalCampWroclaw/organizacyjne/wiki/Informacja-prasowa
